### ISSUE TITLE
KeyError: 'highest_rarity'

### ISSUE THREAD

**Issue by bns34** [PRO100KatYT/SaveTheWorldClaimer#16]
Issue started today:

`[2022/07/09 09:29:05] There are free llamas avaiable!
Traceback (most recent call last):
  File "D:\...\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 429, in <module>
    main()
  File "D:\...\SaveTheWorldClaimer-main\SaveTheWorldClaimer.py", line 367, in main
    llamaTier = reqPopulateLlamas['profileChanges'][0]['profile']['items'][key]['attributes']['highest_rarity']
KeyError: 'highest_rarity'`

I believe it is to do with the latest Fortnite update

**Comment by PRO100KatYT** [comment]
This was already fixed in the 1.9.1 update.
