### ISSUE TITLE
Error opening account manager

### ISSUE THREAD

**Issue by Mrgaton** [PRO100KatYT/SaveTheWorldClaimer#28]
Traceback (most recent call last):
  File "main.py", line 70, in getString
    try: return stringList['Strings'][language][f'{string}']
KeyError: 'startup.managedailyquests.message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 519, in <module>
    if bSkipMainMenu == "false": menu()
  File "main.py", line 334, in menu
    elif bStartClaimer == "2": manageDailyQuests()
  File "main.py", line 295, in manageDailyQuests
    print(getString("startup.managedailyquests.message"))
  File "main.py", line 71, in getString
    except: return stringList['Strings']['en'][f'{string}']
KeyError: 'startup.managedailyquests.message

**Comment by Mrgaton** [comment]
old json problem
